### ISSUE TITLE
I'm unable to make the extension work

### ISSUE THREAD

**Issue by DrDarkDK** [gajananpp/puppeteer-ide-extension#1]
I just installed the extension through [Chrome Web Store](https://chrome.google.com/webstore/detail/puppeteer-ide/ilehdekjacappgghkgmmlbhgbnlkgoid) and tried to use it in my browser without success.
I see the Puppeteer IDE in my developer tools, but it's just white, there's nothing there. This happens on all websites I visit (including Github).
![image](https://user-images.githubusercontent.com/50058655/146787661-58e6060f-e0b0-427e-a26f-579cb4e834da.png)

Any ideas on how I can fix this?

**Comment by gajananpp** [comment]
Can you try refreshing the page, keeping devtools open

**Comment by DrDarkDK** [comment]
Same issue.
I have also tried restarting the entire browser (not just tabs) and disabling all extensions (except Puppeteer of course). Neither helped.

**Comment by DrDarkDK** [comment]
I tried again in Brave, there it works. But not in regular Google Chrome.

**Comment by gajananpp** [comment]
What is Google Chrome version, i will check on that version

**Comment by DrDarkDK** [comment]
96.0.4664.110 (Official Build) (64-bit)

**Comment by gajananpp** [comment]
After opening devtools and switching to Puppeteer IDE tab. Again press Ctrl+Shift+I, which will open devtools for devtools, there in console tab can you check if any errors.

**Comment by DrDarkDK** [comment]
Yep, there were errors:
![image](https://user-images.githubusercontent.com/50058655/146832891-093d0661-bd1b-43ad-82e2-70eebbed15aa.png)

**Comment by gajananpp** [comment]
I was using localStorage to persist script but it seems it's not allowed when cookies are blocked so have made changes to use `chrome.storage` extension api instead of localStorage. You can try extension version 0.0.0.6 once and if you still face this issue feel free to reopen this issue.
